# Generated by Django 3.2.5 on 2021-09-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Check if the email is verified', verbose_name='email_verified'),
        ),
    ]
